/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMP;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author H-p
 */
public class Admin_Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Home_Page
     */
    public Admin_Home_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        ViewProfile = new javax.swing.JMenuItem();
        SearchProfile = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Updatedetails = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Viewattendence = new javax.swing.JMenuItem();
        Takeattendence = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Viewleavedetails = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        Updatesalary = new javax.swing.JMenuItem();
        Payrolldetails = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        Deleteemployee = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();

        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Home Page");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMP/images/Project picture.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1288, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jMenu3.setForeground(new java.awt.Color(0, 153, 255));
        jMenu3.setText("Profile");
        jMenu3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        ViewProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ViewProfile.setAlignmentX(0.0F);
        ViewProfile.setIconTextGap(0);
        ViewProfile.setLabel("View Profile");
        ViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileActionPerformed(evt);
            }
        });
        jMenu3.add(ViewProfile);

        SearchProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchProfile.setText("Search Profile");
        SearchProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchProfileActionPerformed(evt);
            }
        });
        jMenu3.add(SearchProfile);

        jMenuBar2.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 153, 255));
        jMenu4.setText("Manage");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Updatedetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Updatedetails.setText("Update Details");
        Updatedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatedetailsActionPerformed(evt);
            }
        });
        jMenu4.add(Updatedetails);

        jMenuBar2.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(0, 153, 255));
        jMenu5.setText("Attendence");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Viewattendence.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Viewattendence.setText("View Attendence");
        Viewattendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewattendenceActionPerformed(evt);
            }
        });
        jMenu5.add(Viewattendence);

        Takeattendence.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Takeattendence.setText("Take Attendence");
        Takeattendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeattendenceActionPerformed(evt);
            }
        });
        jMenu5.add(Takeattendence);

        jMenuBar2.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(0, 153, 255));
        jMenu6.setText("Leave");
        jMenu6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Viewleavedetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Viewleavedetails.setText("Leave Details");
        Viewleavedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewleavedetailsActionPerformed(evt);
            }
        });
        jMenu6.add(Viewleavedetails);

        jMenuBar2.add(jMenu6);

        jMenu7.setForeground(new java.awt.Color(0, 153, 255));
        jMenu7.setText("Salary");
        jMenu7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Updatesalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Updatesalary.setText("Update Salary");
        Updatesalary.setAutoscrolls(true);
        Updatesalary.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Updatesalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatesalaryActionPerformed(evt);
            }
        });
        jMenu7.add(Updatesalary);

        Payrolldetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Payrolldetails.setText("Payroll Details");
        Payrolldetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayrolldetailsActionPerformed(evt);
            }
        });
        jMenu7.add(Payrolldetails);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Add Employee salary");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar2.add(jMenu7);

        jMenu10.setForeground(new java.awt.Color(0, 153, 255));
        jMenu10.setText("Delete");
        jMenu10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Deleteemployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Deleteemployee.setText("Delete Employee");
        Deleteemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteemployeeActionPerformed(evt);
            }
        });
        jMenu10.add(Deleteemployee);

        jMenuBar2.add(jMenu10);

        jMenu11.setForeground(new java.awt.Color(255, 0, 0));
        jMenu11.setText("Exit");
        jMenu11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu11.add(logout);

        jMenuBar2.add(jMenu11);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 113, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ViewattendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewattendenceActionPerformed
        new View_Attendees().setVisible(true);
    }//GEN-LAST:event_ViewattendenceActionPerformed

    private void ViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileActionPerformed
        new ViewProfileform().setVisible(true);
    }//GEN-LAST:event_ViewProfileActionPerformed

    private void SearchProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchProfileActionPerformed
        new SearchProfileform().setVisible(true);
    }//GEN-LAST:event_SearchProfileActionPerformed

    private void UpdatedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatedetailsActionPerformed
        new Update_details().setVisible(true);
    }//GEN-LAST:event_UpdatedetailsActionPerformed

    private void TakeattendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeattendenceActionPerformed
        new Take_attendence_form().setVisible(true);
    }//GEN-LAST:event_TakeattendenceActionPerformed

    private void ViewleavedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewleavedetailsActionPerformed
       new LeaveManagementSystem().setVisible(true);
    }//GEN-LAST:event_ViewleavedetailsActionPerformed

    private void UpdatesalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatesalaryActionPerformed
        new UpdateSalary().setVisible(true);
    }//GEN-LAST:event_UpdatesalaryActionPerformed

    private void PayrolldetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayrolldetailsActionPerformed
        new Payroll_details().setVisible(true);
    }//GEN-LAST:event_PayrolldetailsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are u sure you want to logout?","Warning",YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(choice ==JOptionPane.YES_OPTION){
            this.setVisible(false);
            new Adminloginform().setVisible(true);
        }
        
    }//GEN-LAST:event_logoutActionPerformed

    private void DeleteemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteemployeeActionPerformed
        new DeleteEmployeeFormm().setVisible(true);
    }//GEN-LAST:event_DeleteemployeeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new addsalaryform().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Deleteemployee;
    private javax.swing.JMenuItem Payrolldetails;
    private javax.swing.JMenuItem SearchProfile;
    private javax.swing.JMenuItem Takeattendence;
    private javax.swing.JMenuItem Updatedetails;
    private javax.swing.JMenuItem Updatesalary;
    private javax.swing.JMenuItem ViewProfile;
    private javax.swing.JMenuItem Viewattendence;
    private javax.swing.JMenuItem Viewleavedetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JMenuItem logout;
    // End of variables declaration//GEN-END:variables
}
