/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMP;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author H-p
 */
public class Employee_home_page extends javax.swing.JFrame {
static String Name;
    /**
     * Creates new form Employee_home_page
     */
    public Employee_home_page(String x) {
        initComponents();
        Employee_home_page.Name=x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        viewprofilemenu = new javax.swing.JMenu();
        profilemenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        leaveapplymenu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Logoutmenu = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home page");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMP/images/Picture 5.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        viewprofilemenu.setText("View");
        viewprofilemenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        profilemenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        profilemenu.setText("View Profile");
        profilemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilemenuActionPerformed(evt);
            }
        });
        viewprofilemenu.add(profilemenu);

        jMenuBar1.add(viewprofilemenu);

        jMenu3.setText("Leave");
        jMenu3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        leaveapplymenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        leaveapplymenu.setText("Apply for leave");
        leaveapplymenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveapplymenuActionPerformed(evt);
            }
        });
        jMenu3.add(leaveapplymenu);

        jMenuBar1.add(jMenu3);

        jMenu5.setForeground(new java.awt.Color(255, 0, 0));
        jMenu5.setText("Exit");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Logoutmenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Logoutmenu.setText("Logout");
        Logoutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutmenuActionPerformed(evt);
            }
        });
        jMenu5.add(Logoutmenu);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profilemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilemenuActionPerformed
        new View_emp_profile(Name).setVisible(true);
    }//GEN-LAST:event_profilemenuActionPerformed

    private void leaveapplymenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveapplymenuActionPerformed
        new Apply_for_leave(Name).setVisible(true);
        
    }//GEN-LAST:event_leaveapplymenuActionPerformed

    private void LogoutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutmenuActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are u sure you want to logout?","Warning",YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(choice ==JOptionPane.YES_OPTION){
           this.setVisible(false);
        new Emp_login().setVisible(true);
        }
    }//GEN-LAST:event_LogoutmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_home_page(Name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Logoutmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem leaveapplymenu;
    private javax.swing.JMenuItem profilemenu;
    private javax.swing.JMenu viewprofilemenu;
    // End of variables declaration//GEN-END:variables
}
